name: Sync Docker Images to Private Registry (Flat Sync)
run-name: Image - ${{ inputs.source_image }}

on:
  workflow_dispatch:
    inputs:
      source_image:
        description: "Source image (e.g. docker.io/golang:1.26.2-bookworm)"
        required: true
        default: "docker.io/golang:1.26.2-bookworm"

jobs:
  sync:
    runs-on: ubuntu-latest 
    steps:
      - name: 🚀 Sync Image using Skopeo
        run: |
          SRC="docker://${{ github.event.inputs.source_image }}"
          TRIM_NAME="$(echo ${{ github.event.inputs.source_image }} | sed -E 's;/;_;g')"
          DEST="docker://${{ secrets.FLAT_PRIVATE_REGISTRY }}/${TRIM_NAME}"
          
          echo "Starting sync: $SRC -> $DEST"

          docker run --rm \
            quay.io/skopeo/stable:latest \
            copy \
            --all \
            --src-tls-verify=true \
            --dest-tls-verify=true \
            --dest-creds "${{ secrets.FLAT_DOCKER_USER }}:${{ secrets.FLAT_DOCKER_TOKEN }}" \
            "$SRC" \
            "$DEST"

      - name: ✅ Done
        run: |
          echo "Image synced successfully to Private Registry."
